package com.gnet.integration.entity.dynamo;

import lombok.Data;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.*;
import java.time.Instant;

@Data
@DynamoDbBean
public class LogsInfo {
    private String logId;
    private String api;
    private String request;
    private String response;
    private Instant createdDate;
    private boolean notified;
    private String supplierId;
    private String extRefNo;
    private long tripReservationId;

    @DynamoDbPartitionKey
    public String getLogId() {
        return logId;
    }

    @DynamoDbSecondaryPartitionKey(indexNames = "api-index")
    public String getApi() {
        return api;
    }

    @DynamoDbSecondaryPartitionKey(indexNames = "response-index")
    public String getResponse() {
        return response;
    }

    @DynamoDbSecondaryPartitionKey(indexNames = "notified-index")
    public boolean isNotified() {
        return notified;
    }

    @DynamoDbAutoGeneratedTimestampAttribute
    public Instant getCreatedDate() {
        return createdDate;
    }
}